name: Run Tests
permissions:
  contents: write
on:
  # Release workflow calls this manually for main and tags
  push:
    branches-ignore:
      - 'main'
  workflow_call: # Can be called from other workflows
jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpunit-polyfills
      # Configure workspace as safe for Git, to solve: https://github.com/composer/composer/issues/12221
      - name: Git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --optimize-autoloader
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: PHPUnit - Run tests for PHP 7.4
        run: bun run test:7.4
      - name: PHPUnit - Run tests for PHP 8.2
        run: bun run test:8.2

      # - name: Jest - Run tests
      #   run: bun run jest:test

      # - name: Install playwright
      #   run: bun playwright install
      # - name: End to end - Run tests
      #   run: bun run e2e
